apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata: # kpt-merge: flux-system/kyverno
  name: kyverno
  namespace: flux-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'source.toolkit.fluxcd.io|HelmRepository|flux-system|kyverno'
spec:
  interval: 5m
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: # kpt-merge: flux-system/kyverno
  name: kyverno
  namespace: flux-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'helm.toolkit.fluxcd.io|HelmRelease|flux-system|kyverno'
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: kyverno
  install:
    createNamespace: true
  chart:
    spec:
      chart: kyverno
      version: '3.2.4'
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 5m
  releaseName: kyverno
